build:
	@echo $(LUA_LIBDIR)
	@echo $(LUA_INCDIR)

install:
	@echo INST_PREFIX: $(INST_PREFIX)
   	@echo INST_BINDIR: $(INST_BINDIR)
   	@echo INST_LIBDIR: $(INST_LIBDIR)
   	@echo INST_LUADIR: $(INST_LUADIR)
   	@echo INST_CONFDIR: $(INST_CONFDIR)
